!obj:pylearn2.train.Train {
  dataset: &train !obj:pylearn2.datasets.mnist.MNIST {
    which_set: 'train',
    start: 0,
    stop:  20000,
    shuffle: True, # doesn't seem to matter all that much
    binarize: True,
  },
  model: !obj:pylearn2.models.mlp.MLP {
    layers: [
      !obj:pylearn2.models.mlp.Tanh {
        layer_name: 'dec_1',
        dim: 784,
        irange: 1,
      },
      !obj:pylearn2.models.mlp.Identity {
        layer_name: 'layer_name',
      }
    ],
    nvis: 784,
  },
  algorithm: !obj:pylearn2.training_algorithms.sgd.SGD {
    learning_rate: 0.01,
    batch_size: 50,
    monitoring_dataset: {
      train: !obj:pylearn2.datasets.mnist.MNIST {
        which_set: 'train',
        start: 0,
        stop:  4000,
        shuffle: True,
        binarize: True,
  },
    },
    cost: !obj:pylearn2.costs.cost.kl_MNIST {
      X: *train,
      n_neighbors: 1000, # Double check with total size of training set
    },
  },
  save_path: '${PYLEARN2_TRAIN_FILE_FULL_STEM}.pkl',
  save_freq: 10,
}